function names=getBasicStatFeatNames(prefix,addLog)

if addLog
    names=[{[prefix,'Mean']}; {[prefix,'StdDev']};...
          {[prefix,'Min']};{[prefix,'Max']};...
          {[prefix,'LogMean']}; {[prefix,'LogStdDev']};...
          {[prefix,'LogMin']};{[prefix,'LogMax']};...
          ];
else
    names=[{[prefix,'Mean']}; {[prefix,'StdDev']};...
          {[prefix,'1-Max']};{[prefix,'Max']};
          ]; 
end